spring:
  data:
    mongodb:
      authentication-database: admin
      username: michal
      password: strongpassword
      database: michal_db
      port: 27017
      host: localhost
  rabbitmq:
    username: michal
    password: strongpassword
    port: 5672
    host: localhost
logging:
  level:
    pl.michal: DEBUG
